name: ART Java Main
on:
  push:
    branches:
      - main
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, windows-latest ]
        jdk: [ 1.8, 11, 17 ]
        tarantool: [ 2.8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: change temp dir
          run: echo "TMPDIR=${{ runner.temp }}" >> $GITHUB_ENV
          shell: bash

      - if: runner.os == 'Windows'
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Debian
          additional-packages:
            aptitude
            sudo

      - if: runner.os == 'macOS'
        name: Initialize the tarantool on OSX
        run: brew install tarantool

      - if: runner.os == 'Windows'
        name: Initialize the tarantool on WSL
        run: |
          wsl bash -c "curl -L https://tarantool.io/KKkJBXq/release/${{ matrix.tarantool }}/installer.sh | bash"
          wsl bash -c "sudo apt-get -y install tarantool"

      - if: runner.os == 'Linux'
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '${{ matrix.tarantool }}'

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --max-workers 8 --parallel

  gradle-publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 1.8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean publish --max-workers 8 --parallel -Ppublisher.username=${publisherUsername} -Ppublisher.password=${publisherPassword} -Pversion=main
        env:
          publisherUsername: ${{ secrets.PUBLISHER_USERNAME }}
          publisherPassword: ${{ secrets.PUBLISHER_PASSWORD }}
